import csv
import logging

from dipper.models.Reference import Reference
from dipper.models.assoc.G2PAssoc import G2PAssoc
from dipper.sources.Source import Source
from dipper.sources.ZFIN import ZFIN
from dipper.models.Model import Model


LOG = logging.getLogger(__name__)
# note: currently no log issued
ZPCURATION = 'http://purl.obolibrary.org/obo/zp/'

class ZFINSlim(Source):
    """
    zfin mgi model only containing Gene to phenotype associations
    Using the file here: https://zfin.org/downloads/phenoGeneCleanData_fish.txt
    """
    files = {
        'g2p_clean': {
            'file': 'phenoGeneCleanData_fish.txt',
            'url': 'https://zfin.org/downloads/phenoGeneCleanData_fish.txt',
            'columns': [
                'ID',
                'Gene Symbol',
                'Gene ID',
                'Affected Structure or Process 1 subterm ID',
                'Affected Structure or Process 1 subterm Name',
                'Post-composed Relationship ID',
                'Post-composed Relationship Name',
                'Affected Structure or Process 1 superterm ID',
                'Affected Structure or Process 1 superterm Name',
                'Phenotype Keyword ID',
                'Phenotype Keyword Name',
                'Phenotype Tag',
                'Affected Structure or Process 2 subterm ID',
                'Affected Structure or Process 2 subterm name',
                'Post-composed Relationship (rel) ID',
                'Post-composed Relationship (rel) Name',
                'Affected Structure or Process 2 superterm ID',
                'Affected Structure or Process 2 superterm name',
                'Fish ID',
                'Fish Display Name',
                'Start Stage ID',
                'End Stage ID',
                'Fish Environment ID',
                'Publication ID',
                'Figure ID',
            ],
        },
        'zpmap': {  # this is a zp mapping file generated by Nico (matches ZIN.py)
            'file': 'id_map_zfin.tsv',
            'url': ZPCURATION + '/id_map_zfin.tsv',
            'columns': [
                'iri',
                'id',
            ]},
    }

    def __init__(self,
                 graph_type,
                 are_bnodes_skolemized,
                 data_release_version=None):
        super().__init__(
            graph_type=graph_type,
            are_bnodes_skized=are_bnodes_skolemized,
            data_release_version=data_release_version,
            name='zfinslim',
            ingest_title='Simplified ZFIN',
            ingest_url='https://zfin.org/',
            ingest_logo="source-zfin.png",
            license_url=None,
            data_rights='http://zfin.org/warranty.html',
            # file_handle=None
        )
        self.dataset.set_citation(
            'https://wiki.zfin.org/display/general/ZFIN+db+information')

    def fetch(self, is_dl_forced=False):
        self.get_files(is_dl_forced)

    def parse(self, limit=None):
        zfin_parser = ZFIN(self.graph_type, self.are_bnodes_skized)
        model = Model(self.graph)

        src_key = 'zpmap'
        zfin_parser.zp_map = zfin_parser._load_zp_mappings(src_key)  # zfin.files[key]

        src_key = 'g2p_clean'
        raw = '/'.join((self.rawdir, self.files['g2p_clean']['file']))
        LOG.info("Processing clean Geno to Pheno from file: %s", raw)


        with open(raw, 'r', encoding="utf8") as csvfile:
            filereader = csv.reader(csvfile, delimiter='\t', quotechar='\"')
            for row in filereader:
                (internal_id,
                 symbol,
                 gene_id,
                 subterm1_id,
                 subterm1_label,
                 pc_rel_id,
                 pc_rel_label,
                 superterm1_id,
                 superterm1_label,
                 quality_id,
                 quality_name,
                 modifier,
                 subterm2_id,
                 subterm2_label,
                 pc_rel2_id,
                 pc_rel2_label,
                 superterm2_id,
                 superterm2_label,
                 fish_id,
                 fish_label,
                 start_stage,
                 end_stage,
                 environment,
                 pub_id,
                 figure_id
                ) = row

                if modifier != "abnormal":
                    LOG.warning("skipping phenotype with modifier != abnormal: " + modifier)
                    continue

                zp_id = zfin_parser._map_octuple_to_phenotype(subterm1_id,
                                                              pc_rel_id,
                                                              superterm1_id,
                                                              quality_id,
                                                              subterm2_id,
                                                              pc_rel2_id,
                                                              superterm2_id,
                                                              modifier)

                gene_curie = "ZFIN:{0}".format(gene_id)
                model.makeLeader(gene_curie)
                pub_curie = "ZFIN:{0}".format(pub_id)
                if zp_id:
                    assoc = G2PAssoc(self.graph, self.name, gene_curie, zp_id)
                    if pub_id:
                        reference = Reference(self.graph, pub_curie,
                                              self.globaltt['document'])
                        reference.addRefToGraph()
                        assoc.add_source(pub_curie)

                    assoc.add_evidence(
                        self.globaltt['experimental phenotypic evidence'])
                    assoc.add_association_to_graph()
